#!/usr/bin/env python3
"""Assigns Actual Budget containers to users by name.

Every user is served by their own Actual Budget container, `actual_<name>`, with
their data in `actual-data/users/<name>`. This script maintains two files:

  config/actual-users.json   email -> name, read by the bridge to route requests
  compose.override.yaml      one Actual container and private network per name

How the containers come to exist depends on whether the provisioner is enabled
(COMPOSE_PROFILES=provisioner in .env):

  Disabled (default)  They are defined in compose.override.yaml, which Docker
                      Compose picks up automatically, and run permanently. Only
                      the users listed here can use Actual Budget.
  Enabled             The provisioner creates them on demand, so this script
                      removes compose.override.yaml and only maintains the names.

Usage:
  scripts/actual-users.py add NAME EMAIL    assign NAME to EMAIL
  scripts/actual-users.py remove NAME       remove NAME (their data is kept)
  scripts/actual-users.py list              show the current assignments
  scripts/actual-users.py sync              rewrite compose.override.yaml, for
                                            example after changing .env

The email must also be allowed by the Cloudflare Access policy for the Actual hostname.
"""

import json
import os
import re
import sys
from pathlib import Path

from dotenv import dotenv_values

# ACTUAL_USERS_ROOT lets the tests work on a copy instead of the real project
ROOT = Path(os.getenv("ACTUAL_USERS_ROOT") or Path(__file__).resolve().parent.parent)
USERS_FILE = ROOT / "config" / "actual-users.json"
OVERRIDE_FILE = ROOT / "compose.override.yaml"
COMPOSE_FILE = ROOT / "compose.yaml"
ENV_FILE = ROOT / ".env"

# Must match NAME_PATTERN in bridge/services/routing_service.py
NAME_PATTERN = re.compile(r"[a-z0-9][a-z0-9-]{0,30}")
PROVISIONER_PROFILE = "provisioner"
STOP_PROVISIONER = (
    "docker compose --profile provisioner rm -sf docker_gateway provisioner"
)
GENERATED_MARKER = (
    "# Generated by scripts/actual-users.py - changes will be overwritten"
)

# The pinned image is defined once, in compose.yaml, and copied from there
IMAGE_DEFAULT_PATTERN = re.compile(r"ACTUAL_IMAGE=(\$\{ACTUAL_IMAGE:-[^}\s]+\})")

# Mirrors the template the provisioner's gateway uses for the containers it creates
SERVICE_TEMPLATE = """\
  actual_{name}:
    image: {image}
    container_name: actual_{name}
    restart: unless-stopped
    volumes:
      - ./actual-data/users/{name}:/data
    networks:
      - actual_static_{name}
    mem_limit: ${{ACTUAL_MEMORY_LIMIT_MB:-512}}m
    cpus: ${{ACTUAL_CPU_LIMIT:-1}}
    pids_limit: ${{ACTUAL_PIDS_LIMIT:-256}}
    cap_drop: [NET_RAW]
    security_opt: [no-new-privileges:true]
"""


def fail(message: str) -> None:
    sys.exit(f"error: {message}")


def load_users() -> dict[str, str]:
    if not USERS_FILE.exists():
        return {}
    users = json.loads(USERS_FILE.read_text())
    if not isinstance(users, dict):
        fail(f"{USERS_FILE} does not contain a JSON object")
    return users


def write_atomically(path: Path, content: str) -> None:
    # Replace the file in one step so nothing ever reads a half-written one
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(content)
    os.replace(temporary, path)


def provisioner_enabled() -> bool:
    """Read the profile setting, preserving shell environment precedence."""
    profiles = os.getenv("COMPOSE_PROFILES")
    if profiles is None:
        profiles = dotenv_values(ENV_FILE).get("COMPOSE_PROFILES")
    return PROVISIONER_PROFILE in {p.strip() for p in (profiles or "").split(",")}


def render_override(names: list[str]) -> str:
    """The Compose override defining a container and a private network per user."""
    match = IMAGE_DEFAULT_PATTERN.search(COMPOSE_FILE.read_text())
    if not match:
        fail(f"could not find the pinned Actual image in {COMPOSE_FILE.name}")

    if not names:
        return f"{GENERATED_MARKER}\nservices: {{}}\n"

    services = "\n".join(
        SERVICE_TEMPLATE.format(name=name, image=match.group(1)) for name in names
    )
    # Caddy and the bridge join every user's network; users never share one
    attachments = "".join(f"      - actual_static_{name}\n" for name in names)
    networks = "".join(f"  actual_static_{name}:\n" for name in names)
    return (
        f"{GENERATED_MARKER}\n"
        f"services:\n{services}\n"
        f"  caddy:\n    networks:\n{attachments}\n"
        f"  flask_bridge:\n    networks:\n{attachments}\n"
        f"networks:\n{networks}"
    )


def sync(users: dict[str, str]) -> None:
    """Brings compose.override.yaml in line with the users and the current mode."""
    exists = OVERRIDE_FILE.exists()
    if exists and GENERATED_MARKER not in OVERRIDE_FILE.read_text():
        fail(f"{OVERRIDE_FILE.name} exists and was not generated by this script")

    if provisioner_enabled():
        # The provisioner creates the containers; static ones would conflict
        if exists:
            OVERRIDE_FILE.unlink()
            print(f"The provisioner is enabled, so {OVERRIDE_FILE.name} was removed.")
            print("Apply with: docker compose up -d --remove-orphans")
        return

    content = render_override(sorted(set(users.values())))
    if not exists or OVERRIDE_FILE.read_text() != content:
        write_atomically(OVERRIDE_FILE, content)
        print(f"Wrote {OVERRIDE_FILE.name}.")
        if not exists:
            # Removing the profile from .env does not stop services already running
            print("If the provisioner was running, stop it first:")
            print(f"  {STOP_PROVISIONER}")
        print("Apply with: docker compose up -d --remove-orphans")


def save(users: dict[str, str]) -> None:
    # Validate and apply the Compose update before publishing routing changes.
    # A rejected override or failed generation must not grant/revoke user access.
    sync(users)
    write_atomically(USERS_FILE, json.dumps(users, indent=2, sort_keys=True) + "\n")


def add(name: str, email: str) -> None:
    email = email.strip().lower()
    if not NAME_PATTERN.fullmatch(name):
        fail("NAME must be lowercase letters, digits and hyphens (max 31 characters)")
    if "@" not in email:
        fail("EMAIL does not look like an email address")

    users = load_users()
    if users.get(email, name) != name:
        fail(f"{email} is already assigned to {users[email]}")

    users[email] = name
    save(users)
    print(f"{email} -> actual_{name}")
    print("Also allow this email in the Cloudflare Access policy for Actual.")


def remove(name: str) -> None:
    users = load_users()
    remaining = {email: n for email, n in users.items() if n != name}
    if len(remaining) == len(users):
        fail(f"no user named {name}")

    save(remaining)
    print(f"Removed {name}. Their data is kept in actual-data/users/{name}.")


def show() -> None:
    users = load_users()
    mode = "enabled" if provisioner_enabled() else "disabled"
    print(f"Provisioner {mode}.")
    if not users:
        print("No users assigned.")
    for email, name in sorted(users.items(), key=lambda item: (item[1], item[0])):
        print(f"actual_{name}\t{email}")


def main(argv: list[str]) -> None:
    command, args = (argv[0], argv[1:]) if argv else (None, [])

    if command == "add" and len(args) == 2:
        add(*args)
    elif command == "remove" and len(args) == 1:
        remove(*args)
    elif command == "list" and not args:
        show()
    elif command == "sync" and not args:
        sync(load_users())
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main(sys.argv[1:])
